{
  "hash": "f5c9aab4fffd466d6806a1af1290ec02",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Medical Statistics – Answers lab 3\"\nformat: \n  html:\n    toc: true       \n    toc-depth: 3    \n    toc-location: right\n  pdf:\n    toc: false      \nexecute:\n  warning: false\n  message: false\n  eval: true\n  echo: false  \n---\n\n\n\n## Part 1: Independent Samples t-test and Mann-Whitney U Test\n\n### Exploratory data analysis\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab3_answers_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 1\"}\nBased on the boxplot, do you expect the smoking status to have an effect on birth weight?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 1\"}\nBased on the boxplot, it appears that mothers who smoked have lower birth weights on average compared to those who did not smoke. This suggests that smoking status may indeed have an effect on birth weight.\n:::\n\n### Independent samples t-test\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  bwt by smoke\nt = 2.6336, df = 187, p-value = 0.009156\nalternative hypothesis: true difference in means between group no and group yes is not equal to 0\n95 percent confidence interval:\n  70.69274 492.73382\nsample estimates:\n mean in group no mean in group yes \n         3054.957          2773.243 \n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 2\"}\nBased on the results of the independent samples t-test, is there a statistically significant difference in birth weight between mothers who smoked and those who did not?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 2\"}\nThe p-value of the independent samples t-test (p=0.009) is less than 0.05, which indicates that there is a statistically significant difference in the mean birth weight between mothers who smoked and those who did not.\n:::\n\n### Checking of assumptions\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab3_answers_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 3\"}\nDo the histograms indicate that the birth weight data are approximately normally distributed for both groups?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 3\"}\nBased on the histograms, the distributions in both groups appear reasonably normal for the purposes of conducting an independent samples t-test.\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   1  1.3901 0.2399\n      187               \n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 4\"}\nBased on Levene's test, does the assumption of equal variances hold?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 4\"}\nThe p-value of Levene's test (p = 0.2399) is greater than 0.05, indicating insufficient evidence to reject the null hypothesis of equal variances. Therefore, we can assume that the assumption of equal variances holds.\n:::\n\n### 95% Confidence Interval for the mean difference\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  smoke  mean    sd     n\n  <fct> <dbl> <dbl> <int>\n1 no    3055.  752.   115\n2 yes   2773.  660.    74\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Exercise\"}\nBased on these summary statistics, calculate the pooled standard deviation and the standard error of the mean difference. Then compute the 95% confidence interval for the mean difference in birth weight between mothers who smoked and those who did not. \n:::\n\n::: {.callout-tip icon=false title=\"Answer\"}\n\n### Calculations for Birth Weight Difference\n\n1. **Pooled Standard Deviation**  \n   The pooled standard deviation is calculated using the formula:  \n   $$\n   s_p = \\sqrt{\\frac{(n_{no} - 1) \\cdot s_{no}^2 + (n_{yes} - 1) \\cdot s_{yes}^2}{n_{no} + n_{yes} - 2}}\n   $$\n   Substituting the values:  \n   $$\n   s_p = \\sqrt{\\frac{(115 - 1) \\cdot 752^2 + (74 - 1) \\cdot 660^2}{115 + 74 - 2}} = 717.49\n   $$\n\n2. **Standard Error of the Mean Difference**  \n   The standard error (SE) of the mean difference is calculated as:  \n   $$\n   SE = s_p \\cdot \\sqrt{\\frac{1}{n_{no}} + \\frac{1}{n_{yes}}}\n   $$\n   Substituting the values:  \n   $$\n   SE = 717.49 \\cdot \\sqrt{\\frac{1}{115} + \\frac{1}{74}} = 106.93\n   $$\n\n3. **Mean Difference**  \n   The difference in means between the groups is:  \n   $$\n   \\text{Mean Difference} = \\bar{X}_{no} - \\bar{X}_{yes} = 3055 - 2773 = 282\n   $$\n\n4. **95% Confidence Interval**  \n   To construct the exact 95% CI, we need the 97.5th percentile from the t-distribution with $115 + 74 - 2 = 187$ degrees of freedom. Since the table in Appendix B does not go beyond 150 df, we use 1.96 (the value from the standard normal distribution) as an approximation. The confidence interval is then calculated as:  \n   $$\n   \\text{CI} = \\text{Mean Difference} \\pm 1.96 \\cdot SE\n   $$\n   Substituting the values:  \n   $$\n   \\text{CI} = 282 \\pm 1.96 \\cdot 106.93 = (72.43, 491.57)\n   $$\n\n### Results\n- **Pooled Standard Deviation:** 717.49  \n- **Standard Error of the Mean Difference:** 106.93  \n- **95% Confidence Interval for the Mean Difference:** (72.43, 491.57)\n:::\n\n::: {.callout-important icon=false title=\"Question 5\"}\nDoes your manually calculated 95% confidence interval for the mean difference in birth weight between the two groups agree with the one provided in the output of the `t.test()` function?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 5\"}\nThe manually calculated 95% confidence interval for the mean difference in birth weight between mothers who smoked and those who did not is (72.43, 491.57), is approximately equal to the one provided in the output of the `t.test()` function, wich is (70.69, 492.73). The latter is marginally wider due to the use of the 97.5 the percentile of the t-distribution with 187 degrees of freedom (1.97) rather than the standard normal distribution (1.96). Additionally, small differences arise from rounding in the manual calculation.\n:::\n\n### Mann-Whitney U Test\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  bwt by smoke\nW = 5243.5, p-value = 0.007109\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 6\"}\nWhat are the null and alternative hypotheses for the Mann-Whitney U test, and what does the p-value indicate about the difference in birth weight between mothers who smoked and those who did not?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 6\"}\nThe null hypothesis for the Mann-Whitney U test is that there is no difference in the median birth weight between mothers who smoked and those who did not. The alternative hypothesis is that there is a difference in median birth weight between the two groups. The p-value of the test is 0.0071, which is less than 0.05. Therefore, we reject the null hypothesis and conclude that there is a statistically significant difference in median birth weight between mothers who smoked and those who did not.\n:::\n\n## Part 2: One-Way ANOVA and Kruskal-Wallis Test\n\n### Explaratory data analysis\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab3_answers_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 7\"}\nWhat does the boxplot suggest about the distribution of birth weights across different ethnic groups?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 7\"}\nThe boxplot suggests that there may be differences in birth weight across the three ehtnic groups. More specifically, The mean birth weight appears to be higher for the Causasian group compared to the Afro-American and Asian groups.\n:::\n\n### One-way ANOVA\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df   Sum Sq Mean Sq F value  Pr(>F)   \nethnicity     2  5070608 2535304   4.972 0.00788 **\nResiduals   186 94846445  509927                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 8\"}\nWhat conclusions can be drawn from the results of the one-way ANOVA?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 8\"}\nThe p-value from the one-way ANOVA (p=0.0079) is less than 0.05, indicating that there is at least one ethic group with a significantly different birth weight.\n:::\n\n### Post-hoc tests\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with pooled SD \n\ndata:  lowbwt$bwt and lowbwt$ethnicity \n\n              Caucasian Afro-American\nAfro-American 0.048     -            \nAsian         0.027     1.000        \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 9\"}\nWhat conclusions can be drawn from the post-hoc comparisons?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 9\"}\nIt follows from the post-hoc comparisons with the Bonferroni-adjusted p-values that the mean birth weight of Caucasian infants is significantly different from that of Afro-American infants (p=0.048) and Asian infants (p=0.027). There is no significant difference in mean birth weight between Afro-American and Asian infants (p=1).\n:::\n\n### Kruskal-Wallis Test\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  bwt by ethnicity\nKruskal-Wallis chi-squared = 8.5909, df = 2, p-value = 0.01363\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 10\"}\nAre the results of the Kruskal-Wallis test consistent with the one-way ANOVA results? \n:::\n\n::: {.callout-tip icon=false title=\"Answer question 10\"}\nThe p-value from the Kruskal-Wallis test (p=0.014) is consistent with the one-way ANOVA results, indicating that there is at least one ethnic group with a significantly different median birth weight.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Kruskal-Wallis rank sum test\n\ndata: x and group\nKruskal-Wallis chi-squared = 8.5909, df = 2, p-value = 0.01\n\n                           Comparison of x by group                            \n                                 (Bonferroni)                                  \nCol Mean-|\nRow Mean |   Afro-Ame      Asian\n---------+----------------------\n   Asian |  -0.667476\n         |     1.0000\n         |\nCaucasia |  -2.380803  -2.337641\n         |     0.0518     0.0582\n\nalpha = 0.05\nReject Ho if p <= alpha\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$chi2\n[1] 8.590907\n\n$Z\n[1] -0.6674762 -2.3808031 -2.3376414\n\n$altP\n[1] 0.50446798 0.01727494 0.01940586\n\n$altP.adjusted\n[1] 1.00000000 0.05182482 0.05821758\n\n$comparisons\n[1] \"Afro-American - Asian\"     \"Afro-American - Caucasian\"\n[3] \"Asian - Caucasian\"        \n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 11\"}\nWhat conclusions can be drawn from Dunn's test? Are these consistent with the post-hoc comparisons from the one-way ANOVA?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 11\"}\nUnlike the post-hoc comparisons from the one-way ANOVA, Dunn's test with Bonferroni correction does not show statistically significant differences between any pair of groups at the 0.05 level. Although the adjusted p-values for Caucasian vs. Afro-American (p=0.052) and Caucasian vs. Asian (p=0.058) are close to 0.05, they do not reach statistical significance. This illustrates that non-parametric post-hoc tests can be more conservative than their parametric counterparts.\n:::\n\n## Part 3: Unguided exercises\n\n### Effect of hypertension on birth weight\n\nExamine the effect of history of hypertension on birth weight by performing the following steps:\n\n- Create a boxplot to visualize the distribution of birth weights by history of hypertension\n- Perform an independent samples t-test to compare the mean birth weights between mothers with and without a history of hypertension\n- Check the assumptions of the t-test, including normality and homogeneity of variances\n- If the assumptions of the t-test are violated, perform a Mann-Whitney U test as a non-parametric alternative\n\n### Example solution\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab3_answers_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  bwt by ht\nt = 2.0192, df = 187, p-value = 0.04489\nalternative hypothesis: true difference in means between group no and group yes is not equal to 0\n95 percent confidence interval:\n  10.02413 861.09734\nsample estimates:\n mean in group no mean in group yes \n         2972.311          2536.750 \n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lab3_answers_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   1  1.2851 0.2584\n      187               \n```\n\n\n:::\n:::\n\n\n**Evaluation of the results**: Although the p-value from the independent samples t-test suggests that there is no statistically significant difference in birth weight between mothers with and without a history of hypertension, the group sizes are highly imbalanced (177 vs. 12). This imbalance reduces the reliability of the t-test results and may limit its power to detect true differences. Additionally, the small sample size in the hypertension group makes it harder to assess assumptions such as normality. To check the robustness of the findings, we also conduct the Mann-Whitney U test as a non-parametric alternative.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  bwt by ht\nW = 1350, p-value = 0.1169\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\n**Overall conclusion**: Both the independent samples t-test and the Mann-Whitney U test suggest that there is no statistically significant difference in birth weight between mothers with and without a history of hypertension. This consistency across methods supports the robustness of the findings, despite the imbalance in group sizes.\n\n### Comparing red cell folate levels across ventilation strategies in cardiac bypass patients\n\nTwenty-two patients undergoing cardiac bypass surgery were randomized to one of three ventilation groups:\n\n- **Group I**: Received a 50% nitrous oxide and 50% oxygen mixture continuously for 24 hours\n- **Group II**: Received a 50% nitrous oxide and 50% oxygen mixture only during the operation\n- **Group III**: Received no nitrous oxide and a 35-50% oxygen mixture continuously for 24 hours\n\nThe data file `ex5_6.sav` (available on Brightspace) contains the red cell folate levels for the three groups after 24 hours of ventilation. The aim of this study is to compare the three groups and test whether they have the same red cell folate levels.\n\n#### Tasks\n\n1. **Exploratory data analysis**  Create a boxplot to visualize the distribution of red cell folate levels by ventilation group. Based on this plot:\n   - What are your first conclusions regarding the means and variances of the different groups?\n2. **Perform a one-way ANOVA**:\n   - Interpret the results\n   - Are the assumptions satisfied?\n3. **Try a log transformation on the data**:\n   - Perform another one-way ANOVA\n   - Are the assumptions satisfied after the transformation?\n4. **Determine which means differ**:\n   - Which means do you think differ?\n   - Explain your reasoning.\n5. **Try a non-parametric approach**:\n   - What are your conclusions from this method?\n\n\n### Example solution\n\n#### Exploratory data analysis\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab3_answers_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe groups seem to be different with respect to their means, but also with respect to their variation (range has different length)\n\n#### Perform a one way ANOVA, and interpret the results. Are the conditions satisfied?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \ngroup        2  15516    7758   3.711 0.0436 *\nResiduals   19  39716    2090                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value  Pr(>F)  \ngroup  2  3.6413 0.04585 *\n      19                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe ANOVA reveals significant results P= 0.044; this means that the null hypothesis of equal means in the three groups is rejected. However, according to the test of homogeneity of variances, the assumption of equal variances is violated (P-value = 0.044).\n\n#### Try a log transformation on the data, and perform again a one-way ANOVA. Are now the assumptions satisfied?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)  \ngroup        2 0.1784 0.08922   3.539 0.0494 *\nResiduals   19 0.4790 0.02521                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  2   1.889 0.1785\n      19               \n```\n\n\n:::\n:::\n\nThe test of equal variances for the log-transformed data reveals that the assumption of equal variances can be made. Test results for the ANOVA: P-value = 0.049. This is on the boundary of significance. There is indication that at least one pair of groups have different means.\n\n#### Which means do differ according to you? Why?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with pooled SD \n\ndata:  df$rcfl and df$group \n\n        Group 1 Group 2\nGroup 2 0.042   -      \nGroup 3 0.464   1.000  \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with pooled SD \n\ndata:  df$log_rcfl and df$group \n\n        Group 1 Group 2\nGroup 2 0.047   -      \nGroup 3 0.597   1.000  \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\nFrom the paired comparisons with Bonferroni-corrections it appears that group1 and group 2 differ significantly with respect to their means (but on the boundary, P-value = 0.047).\n\n(e) Try a non-parametric approach on these data. What are now your conclusions?\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  rcfl by group\nKruskal-Wallis chi-squared = 4.1852, df = 2, p-value = 0.1234\n```\n\n\n:::\n:::\n\n\nThe Kruskal-Wallis test gives P-value = 0.123, indicating that there are no significant differences between the three groups.\n\n#### Caveat \n\nIn this example, the sample size is very limited, making it difficult — if not impossible — to verify whether the assumptions underlying the one-way ANOVA are met. The Kruskal-Wallis test is a good alternative in such cases.\n\n\n\n",
    "supporting": [
      "lab3_answers_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}