{
  "hash": "7618df2f1ec64424a8c525a2720e48ab",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Medical Statistics – Answers lab 7\"\nformat:\n  html:\n    toc: true       \n    toc-depth: 3    \n    toc-location: right\n    code-overflow: wrap \n  pdf:\n    toc: false\nexecute:\n  warning: false\n  message: false\n  error: false\n  eval: true\n  echo: false\n---\n\n## Part 1: Risk of in-hospital death in patients with acute myocardial infarction\n\n\n::: {.cell}\n\n:::\n\n\n### Exploratory data analysis\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         alive dead\n  male     282   18\n  female   179   21\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         alive  dead\n  male   0.940 0.060\n  female 0.895 0.105\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 1\"}\nBased on the group proportions, do you expect gender to have an effect on the risk of in-hospital death?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 1\"}\nThe proportion of in-hospital deaths is higher among females (0.105) than among females (0.06). This suggests that gender might be associated with the risk of in-hospital death.  \n:::\n\n### Simple logistic regression\n\n::: {.callout-important icon=false title=\"Question 2\"}\nPerform the chi-square test of homogeneity (see instructions in lab 4 if needed). What conclusion can be drawn from the test?\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  contingencyTable\nX-squared = 3.3789, df = 1, p-value = 0.06603\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=false title=\"Answer question 2\"}\nThe p-value of the chi-square test (0.066) is larger than 0.05, indicating that there is no significant association between gender and in-hospital death.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = dstat_numeric ~ gender, family = binomial, data = whas500)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -2.7515     0.2431 -11.318   <2e-16 ***\ngenderfemale   0.6087     0.3351   1.816   0.0693 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 273.86  on 499  degrees of freedom\nResidual deviance: 270.55  on 498  degrees of freedom\nAIC: 274.55\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 3\"}\nWhat is the odds ratio for in-hospital death for females compared to males? How should this odds ratio be interpreted in the context of the study? \n:::\n\n::: {.callout-tip icon=false title=\"Answer question 3\"}\nThe odds ratio for in-hospital death for females compared to males is equal to $\\exp(0.6087) = 1.83$. This means that the odds of in-hospital death are 1.83 times higher in females than in males.\n:::\n\n::: {.callout-important icon=false title=\"Question 4\"}\nBased on the estimated regression coefficients (ignoring p-values), what are the predicted proportions of in-hospital deaths for male and female patients? Compare the predicted proportions to the observed proportions from the previously constructed contingency table. Do they match?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 4\"}\nThe linear predictor models the risk of in-hospital death on the log-odds scale. To obtain the predicted probabilities, we need to transform the log-odds back to the probability scale using the logistic function. \n\nThe predicted probabilities of in-hospital death on the log-odds scale are:\n\n- Males: -2.7515 (intercept)\n- Females: -2.7515 + 0.6087 (intercept + coefficient) = -2.1428\n\nThe predicted probabilities on the probability scale are:\n\n- Male: $1 / (1 + exp(-(-2.7515))) = 0.060$\n- Female: $1 / (1 + exp(-(-2.1428))) = 0.105$\n\nThe predicted proportions of in-hospital deaths match the observed proportions from the contingency table.\n:::\n\n::: {.callout-important icon=false title=\"Question 5\"}\nWhat conclusion can be drawn from the logistic regression analysis regarding the association between gender and in-hospital death? Is this in line with the conclusion drawn from the chi-square test?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 5\"}\nThe p-value of the Wald test for the regression coefficient of the dummy variable `genderfemale` is 0.069, which is larger than 0.05. This indicates that there is no significant association between gender and in-hospital death. This conclusion is consistent with the results of the chi-square test.\n:::\n\n### Multiple logistic regression\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = dstat_numeric ~ gender + age, family = binomial, \n    data = whas500)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -6.89600    1.19131  -5.789  7.1e-09 ***\ngenderfemale  0.26776    0.34618   0.773 0.439246    \nage           0.05770    0.01524   3.785 0.000154 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 273.86  on 499  degrees of freedom\nResidual deviance: 253.45  on 497  degrees of freedom\nAIC: 259.45\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 6\"}\nHow does adjusting for age affect the estimated odds ratio for in-hospital death for females compared to males?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 6\"}\nAfter adjusting for age, the odds ratio for in-hospital death for females compared to males decreases from 1.83 to $\\exp(0.26776) = 1.31$. This indicates that the effect of gender on in-hospital death is confounded by age.\n:::\n\n::: {.callout-important icon=false title=\"Question 7\"}\nCalculate the odds ratio for in-hospital death corresponding to a 10-year increase in age and interpret its meaning.\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 7\"}\nThe increase in the risk of in-hospital death on the log-odds scale is equal to 0.0577 * 10 = 0.577. This means that for every 10-year increase in age, the odds of in-hospital death increase by a factor of $\\exp(0.577) = 1.78$.\n:::\n\n### Likelihood ratio tests\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: dstat_numeric ~ age\nModel 2: dstat_numeric ~ gender + age\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1       498     254.05                     \n2       497     253.45  1  0.59934   0.4388\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 8\"}\nHow does the p-value from the likelihood ratio test compare to the one from the Wald test?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 8\"}\nThe p-value of the likelihood ratio test (0.4388) is approximately equal to the p-value of the Wald test (0.4392). This indicates that the results of the two tests are consistent, which is expected because, for testing the significance of a single coefficient, the Wald test and the likelihood ratio test often yield similar results. However, they are not strictly equivalent, as the likelihood ratio test is based on comparing model fit, while the Wald test assesses the coefficient's deviation from zero using its standard error.\n:::\n\n### Evaluating model fit\n\n#### R results\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nGroups for Hosmer-Lemeshow C statistic:\ncutfit\n[0.00568,0.0178]  (0.0178,0.0279]  (0.0279,0.0369]  (0.0369,0.0514] \n              55               52               47               52 \n  (0.0514,0.065]   (0.065,0.0864]   (0.0864,0.103]    (0.103,0.126] \n              44               53               55               43 \n   (0.126,0.154]    (0.154,0.348] \n              50               49 \nGroups for Hosmer-Lemeshow H statistic:\ncutfit1\n[0.00534,0.0399]  (0.0399,0.0742]   (0.0742,0.108]    (0.108,0.143] \n             164              110               87               61 \n   (0.143,0.177]    (0.177,0.211]    (0.211,0.245]     (0.245,0.28] \n              54               19                2                2 \n    (0.28,0.314]    (0.314,0.348] \n               0                1 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$C\n\n\tHosmer-Lemeshow C statistic\n\ndata:  fitted(model.sex.age) and model.sex.age$y\nX-squared = 11.465, df = 8, p-value = 0.1767\n\n\n$H\n\n\tHosmer-Lemeshow H statistic\n\ndata:  fitted(model.sex.age) and model.sex.age$y\nX-squared = 6.2434, df = 8, p-value = 0.62\n```\n\n\n:::\n:::\n\n\n#### SPSS results\n\n![Screenshot of the Hosmer-Lemeshow test results in SPSS](images/SPSS_lab8_q9.PNG)\n\n::: {.callout-important icon=false title=\"Question 9\"}\nBased on the results of the Hosmer-Lemeshow goodness-of-fit test, does our model provide a satisfactory fit to the data?\n:::  \n   \n::: {.callout-tip icon=false title=\"Answer question 9\"}\nThe p-value for the Hosmer-Lemeshow test is 0.177 in R (C statistic) and 0.120 in SPSS, indicating that the model provides a satisfactory fit to the data: a non-significant p-value suggests that the model fits the data well, meaning that the observed and expected frequencies do not differ significantly. \n\nNote: the discrepancy between the p-values from R and SPSS seems to be due to small differences in how the groups are created within the implementation of the test. \n:::   \n     \n## Part 2: unguided exercises\n\n### Exercise 1\n\nMultiple logistic regression was used to construct a prognostic index to predict coronary artery disease from data on 348 patients with valvular heart disease who had undergone routine coronary arteriography before valve replacement (Ramsdale et al. 1982). The estimated equation was:\n\n$$logit(p) = ln(p/(1-p)) = b_{0} + 1.167 \\times x{1} + 0.0106 \\times x_{2} + \\textrm{other terms}$$\n\nwhere $x_{1}$ stands for the family history of ischaemic disease (0=no, 1=yes) and $x_{2}$ is the estimated total number of cigarettes ever smoked in terms of thousand cigarettes, calculated as the average number smoked annually times the number of years smoking.\n\n(a)\tWhat is the estimated odds ratio for having coronary artery disease for subjects with a positive family history relative to subjects with a negative family history?\n(b)\tWhat total number of cigarettes ever smoked carries the same risk as a positive family history? Convert the result into years of smoking 20 cigarettes per day.\n(c)\tWhat is the odds ratio for coronary artery disease for someone with a positive family history who had smoked 20 cigarettes a day for 30 years compared to a non smoker with no family history?\n\n**Answers:**\n\n(a) $\\exp(1.167) = 3.212$.\n\n(b) The log(OR) of positive history, $1.167$, is to be set equal to $0.0106 \\times x_2$, where $0.0106$ is the log odds ratio of smoking 1000 cigarettes. Thus $x_2=1.167/0.0106=110.094$ thousands of cigarettes. Dividing this result by $(365 \\times 20) / 1000 = 7.3$, i.e., the total number cigarettes (per thousand) smoked in 1 year if smoking 20 cigarettes per day, we find $110.094/7.3=15.1$ or just above 15 years. Thus the odds ratio of positive history is equivalent to that of daily smoking of 20 cigarettes for about 15 years.\n\n(c) The total number of cigarettes smoked (per thousand) is $(20 \\times 365 \\times 30) / 1000 = 219$, so the odds ratio is $\\exp(1.167 + 219 \\times 0.0106) = 32.7$\n\n### Exercise 2\n\nData from 37 patients receiving a non-depleted allogenic bone marrow transplant were examined to see which variables were associated with the occurrence of acute graft-versus-host disease (GvHD: 0=no, 1=yes) (Bagot et al., 1988). Possible predictors are TYPE (type of leukemia: 1=AML, acute myeloid leukaemia; 2=ALL, acute lymphocytic leukaemia; 3=CML, chronic myeloid leukemia), PREG (donor pregnancy: 0= no, 1=yes), and LOGIND (the logarithm of an index of mixed epidermal cell-lymphocyte reactions). The data are in the file `GvHD.sav` available on Brightspace.\n\n(a) Perform a likelihood ratio test to determine whether there is a significant association between the type of leukemia and the occurrence of GvHD after adjusting for donor pregnancy and the logarithm of an index of mixed epidermal cell-lymphocyte reactions.\n(b) In the adjusted model, What is the estimated odds ratio for the occurrence of GvHD for patients with ALL compared to those with ALM?\n(c) Use the Hosmer-Lemeshow goodness-of-fit test to evaluate the fit of the model. Based on the results, does the model provide a satisfactory fit to the data?\n\n**Answers:**\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a 0/1 numeric version of the outcome variable\nGvHD$gvhd.numeric <- ifelse(GvHD$gvhd == \"no\", 0, 1)\n\n# Fit the full  model\nmodel.GvHD <- glm(gvhd.numeric ~ type + preg + logind, family = binomial, data = GvHD)\nsummary(model.GvHD)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = gvhd.numeric ~ type + preg + logind, family = binomial, \n    data = GvHD)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)  -2.4496     1.2113  -2.022   0.0431 *\ntypeALL      -0.1480     1.1722  -0.126   0.8996  \ntypeCML       2.1781     1.2420   1.754   0.0795 .\npregyes       2.4982     1.1026   2.266   0.0235 *\nlogind        1.4577     0.7547   1.932   0.0534 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 51.049  on 36  degrees of freedom\nResidual deviance: 28.832  on 32  degrees of freedom\nAIC: 38.832\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fit the reduced model\nmodel.GvHD.reduced <- glm(gvhd.numeric ~ preg + logind, family = binomial, data = GvHD)\n\n# Perform likelihood ratio test\nanova(model.GvHD.reduced, model.GvHD, test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: gvhd.numeric ~ preg + logind\nModel 2: gvhd.numeric ~ type + preg + logind\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)  \n1        34     33.654                       \n2        32     28.832  2    4.822  0.08972 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n(a) The p-value of the likelihood ratio test is 0.090, indicating that the type of leukemia is not significantly associated with the occurrence of GvHD after adjusting for donor pregnancy and the logarithm of an index of mixed epidermal cell-lymphocyte reactions.\n\n(b) By default, R and SPSS both use the first level of the factor (`ALM`) as the reference category. Therefore, the table with estimated regression coefficients is the same in both outputs. The estimated odds ratio for the occurrence of GvHD for patients with AML compared to those with ALL is $\\exp(-0.148) = 0.862$.\n\n(c) The Hosmer-Lemeshow test results are as follows:\n\n#### R\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nGroups for Hosmer-Lemeshow C statistic:\ncutfit\n[0.0109,0.0254] (0.0254,0.0552]  (0.0552,0.142]   (0.142,0.237]   (0.237,0.529] \n              4               4               3               4               4 \n  (0.529,0.582]   (0.582,0.756]   (0.756,0.879]   (0.879,0.891]   (0.891,0.988] \n              3               4               3               4               4 \nGroups for Hosmer-Lemeshow H statistic:\ncutfit1\n[0.00994,0.109]   (0.109,0.206]   (0.206,0.304]   (0.304,0.402]     (0.402,0.5] \n             11               2               3               1               1 \n    (0.5,0.597]   (0.597,0.695]   (0.695,0.793]    (0.793,0.89]    (0.89,0.989] \n              5               0               4               6               4 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$C\n\n\tHosmer-Lemeshow C statistic\n\ndata:  fitted(model.GvHD) and GvHD$gvhd.numeric\nX-squared = 12.352, df = 8, p-value = 0.1362\n\n\n$H\n\n\tHosmer-Lemeshow H statistic\n\ndata:  fitted(model.GvHD) and GvHD$gvhd.numeric\nX-squared = 14.907, df = 8, p-value = 0.06097\n```\n\n\n:::\n:::\n\n\n#### SPSS\n\n![Screenshot of the Hosmer-Lemeshow test results in SPSS](images/SPSS_lab8_ex2.PNG)\n\nWhile R and SPSS produce different p-values, neither is significant. Therefore, the model provides a satisfactory fit to the data.\n\n",
    "supporting": [
      "lab7_answers_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}