{
  "hash": "3b587bc6e563d175879b648c922b8318",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Medical Statistics - Answers lab 5\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-location: right\n  pdf:\n    toc: false\nexecute:\n  warning: false\n  message: false\n  error: false\n  eval: true\n---\n\n## Introduction\n\nThis answer page gives one complete set of answers for lab 5. The same numerical results should be obtained when the analyses are carried out in R or SPSS.\n\nThe analyses use the Cleveland heart disease dataset and address the following research questions:\n\n* Does maximum heart rate achieved differ across chest pain types?\n* Is the presence of heart disease associated with sex?\n* Is the presence of heart disease associated with fasting blood sugar?\n\n## Exercise 1: Download and open the dataset\n\nThe dataset contains 303 patients and 14 variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\nlibrary(knitr)\nlibrary(tableone)\nlibrary(car)\nlibrary(dunn.test)\n\nheart_data <- as.data.frame(read_sav(\"datasets/heart_disease_cleveland.sav\"))\n\n# Convert labelled categorical variables to factors.\nlabelled_vars <- vapply(heart_data, haven::is.labelled, logical(1))\nheart_data[labelled_vars] <- lapply(heart_data[labelled_vars], haven::as_factor)\n\ndim(heart_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 303  14\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(heart_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"age\"      \"sex\"      \"cp\"       \"trestbps\" \"chol\"     \"fbs\"     \n [7] \"restecg\"  \"thalach\"  \"exang\"    \"oldpeak\"  \"slope\"    \"ca\"      \n[13] \"thal\"     \"target\"  \n```\n\n\n:::\n:::\n\n\nThe variables `sex`, `cp`, `fbs`, `restecg`, `exang`, `slope`, `thal`, and `target` are categorical. The variable `ca` is also best treated as categorical for the baseline table, because it records the number of major vessels from 0 to 3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheart_data$ca <- factor(heart_data$ca)\n```\n:::\n\n\n## Exercise 2: Create a baseline characteristics table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontinuous_vars <- c(\"age\", \"trestbps\", \"chol\", \"thalach\", \"oldpeak\")\ncategorical_vars <- c(\"sex\", \"cp\", \"fbs\", \"restecg\", \"exang\", \"slope\", \"ca\", \"thal\")\nall_vars <- c(continuous_vars, categorical_vars)\n\ntable1 <- CreateTableOne(\n  vars = all_vars,\n  data = heart_data,\n  factorVars = categorical_vars\n)\n\nkable(\n  print(\n    table1,\n    nonnormal = \"oldpeak\",\n    printToggle = FALSE\n  )\n)\n```\n\n::: {.cell-output-display}\n\n\n|                             |Overall           |\n|:----------------------------|:-----------------|\n|n                            |303               |\n|age (mean (SD))              |54.44 (9.04)      |\n|trestbps (mean (SD))         |131.69 (17.60)    |\n|chol (mean (SD))             |246.69 (51.78)    |\n|thalach (mean (SD))          |149.61 (22.88)    |\n|oldpeak (median [IQR])       |0.80 [0.00, 1.60] |\n|sex = Male (%)               |206 (68.0)        |\n|cp (%)                       |                  |\n|Typical angina               |23 ( 7.6)         |\n|Atypical angina              |50 (16.5)         |\n|Non-anginal pain             |86 (28.4)         |\n|Asymptomatic                 |144 (47.5)        |\n|fbs = True (%)               |45 (14.9)         |\n|restecg (%)                  |                  |\n|Normal                       |151 (49.8)        |\n|ST-T wave abnormality        |4 ( 1.3)          |\n|Left ventricular hypertrophy |148 (48.8)        |\n|exang = Yes (%)              |99 (32.7)         |\n|slope (%)                    |                  |\n|Upsloping                    |142 (46.9)        |\n|Flat                         |140 (46.2)        |\n|Downsloping                  |21 ( 6.9)         |\n|ca (%)                       |                  |\n|0                            |176 (58.9)        |\n|1                            |65 (21.7)         |\n|2                            |38 (12.7)         |\n|3                            |20 ( 6.7)         |\n|thal (%)                     |                  |\n|Normal                       |166 (54.8)        |\n|Fixed defect                 |20 ( 6.6)         |\n|Reversible defect            |117 (38.6)        |\n\n\n:::\n:::\n\n\nA suitable baseline table gives one summary format per variable. In the table above, most continuous variables are summarized using mean and standard deviation, `oldpeak` is summarized using median and interquartile range because it is clearly skewed, and categorical variables are summarized using counts and percentages.\n\n## Exercise 3: Analyze maximum heart rate across chest pain types\n\nResearch question: *Does maximum heart rate achieved differ across chest pain types?*\n\nThe outcome is `thalach`, and the grouping variable is `cp`.\n\n### Descriptive results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(\n  thalach ~ cp,\n  data = heart_data,\n  xlab = \"Chest pain type\",\n  ylab = \"Maximum heart rate achieved\",\n  las = 2\n)\n```\n\n::: {.cell-output-display}\n![](lab5_answers_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (group in levels(heart_data$cp)) {\n  group_data <- heart_data$thalach[heart_data$cp == group]\n  n <- length(group_data)\n  mean_thalach <- mean(group_data)\n  se_thalach <- sd(group_data) / sqrt(n)\n  ci_thalach <- mean_thalach + c(-1, 1) * qt(0.975, df = n - 1) * se_thalach\n\n  cat(\n    group,\n    \": n =\", n,\n    \", mean =\", round(mean_thalach, 1),\n    \", 95% CI = [\", round(ci_thalach[1], 1), \", \", round(ci_thalach[2], 1), \"]\\n\",\n    sep = \"\"\n  )\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTypical angina: n =23, mean =156, 95% CI = [146.9, 165]\nAtypical angina: n =50, mean =162.4, 95% CI = [157, 167.8]\nNon-anginal pain: n =86, mean =155.4, 95% CI = [151.3, 159.5]\nAsymptomatic: n =144, mean =140.7, 95% CI = [136.9, 144.5]\n```\n\n\n:::\n:::\n\n\nThe mean maximum heart rate was lowest in the asymptomatic chest pain group.\n\n### One-way ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_model <- aov(thalach ~ cp, data = heart_data)\nsummary(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \ncp            3  23503    7834   17.41 1.91e-10 ***\nResiduals   299 134523     450                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe one-way ANOVA is statistically significant, $F(3, 299) = 17.41$, $p < 0.001$. This indicates that maximum heart rate achieved differs across chest pain types.\n\n### Assumption checks\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nhist(heart_data$thalach[heart_data$cp == \"Typical angina\"],\n     main = \"Typical angina\", xlab = \"Maximum heart rate\")\nhist(heart_data$thalach[heart_data$cp == \"Atypical angina\"],\n     main = \"Atypical angina\", xlab = \"Maximum heart rate\")\nhist(heart_data$thalach[heart_data$cp == \"Non-anginal pain\"],\n     main = \"Non-anginal pain\", xlab = \"Maximum heart rate\")\nhist(heart_data$thalach[heart_data$cp == \"Asymptomatic\"],\n     main = \"Asymptomatic\", xlab = \"Maximum heart rate\")\n```\n\n::: {.cell-output-display}\n![](lab5_answers_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\nqqnorm(residuals(anova_model))\nqqline(residuals(anova_model))\n```\n\n::: {.cell-output-display}\n![](lab5_answers_files/figure-pdf/unnamed-chunk-7-2.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ntapply(heart_data$thalach, heart_data$cp, sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Typical angina  Atypical angina Non-anginal pain     Asymptomatic \n        20.89906         18.98882         19.31679         22.98210 \n```\n\n\n:::\n\n```{.r .cell-code}\nleveneTest(thalach ~ cp, data = heart_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value  Pr(>F)  \ngroup   3  2.4694 0.06209 .\n      299                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe histograms and Q-Q plot can be used to assess whether the distributions are roughly compatible with ANOVA. There is no need to base this decision on a formal test of normality; with these sample sizes such tests are often not helpful for deciding which analysis to use. The group standard deviations are of a similar order of magnitude, and Levene's test does not show evidence against the equal variances assumption.\n\n### Post-hoc comparisons\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.t.test(\n  heart_data$thalach,\n  heart_data$cp,\n  p.adjust.method = \"bonferroni\",\n  pool.sd = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with pooled SD \n\ndata:  heart_data$thalach and heart_data$cp \n\n                 Typical angina Atypical angina Non-anginal pain\nAtypical angina  1.0000         -               -               \nNon-anginal pain 1.0000         0.3840          -               \nAsymptomatic     0.0089         8.8e-09         3.7e-06         \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\nUsing Bonferroni-adjusted pairwise t-tests, the asymptomatic chest pain group has a significantly lower maximum heart rate than the typical angina group, the atypical angina group, and the non-anginal pain group. The other pairwise comparisons are not statistically significant after Bonferroni adjustment.\n\n### Kruskal-Wallis sensitivity analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(thalach ~ cp, data = heart_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  thalach by cp\nKruskal-Wallis chi-squared = 47.315, df = 3, p-value = 2.979e-10\n```\n\n\n:::\n\n```{.r .cell-code}\ndunn.test(\n  heart_data$thalach,\n  heart_data$cp,\n  method = \"bonferroni\",\n  altp = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Kruskal-Wallis rank sum test\n\ndata: x and group\nKruskal-Wallis chi-squared = 47.3151, df = 3, p-value = 0\n\n                           Comparison of x by group                            \n                                 (Bonferroni)                                  \nCol Mean-|\nRow Mean |   Asymptom   Atypical   Non-angi\n---------+---------------------------------\nAtypical |  -5.970501\n         |    0.0000*\n         |\nNon-angi |  -4.836917   1.804218\n         |    0.0000*     0.4272\n         |\nTypical  |  -2.983404   1.230885  -0.045777\n         |    0.0171*     1.0000     1.0000\n\nalpha = 0.05\nReject Ho if p <= alpha\n```\n\n\n:::\n:::\n\n\nThe Kruskal-Wallis test gives the same substantive conclusion, $\\chi^2(3) = 47.32$, $p < 0.001$. The Bonferroni-adjusted Dunn's test again shows that the asymptomatic group differs from the other three chest pain groups.\n\n## Exercise 4: Analyze heart disease by sex\n\nResearch question: *Is the presence of heart disease associated with sex?*\n\n::: {.callout-note}\nFor the 2x2 tables in this lab, `chisq.test(..., correct = FALSE)` is used to report the ordinary Pearson chi-square test. This corresponds to the **Pearson Chi-Square** row in SPSS. If `correct = FALSE` is omitted, R applies Yates' continuity correction by default for 2x2 tables; SPSS reports this separately as **Continuity Correction**.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_table <- table(heart_data$sex, heart_data$target)\nsex_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         Heart Disease No Heart Disease\n  Female            25               72\n  Male             114               92\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(sex_table, margin = 1) * 100, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         Heart Disease No Heart Disease\n  Female          25.8             74.2\n  Male            55.3             44.7\n```\n\n\n:::\n:::\n\n\nThe row percentages show that the prevalence of heart disease was higher in males than in females.\n\nThe expected cell counts are all larger than 5, so the chi-square test is appropriate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsex_chisq <- chisq.test(sex_table, correct = FALSE)\nsex_chisq$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        \n         Heart Disease No Heart Disease\n  Female      44.49835         52.50165\n  Male        94.50165        111.49835\n```\n\n\n:::\n\n```{.r .cell-code}\nsex_chisq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  sex_table\nX-squared = 23.218, df = 1, p-value = 1.446e-06\n```\n\n\n:::\n:::\n\n\nThere is strong evidence of an association between sex and heart disease, $\\chi^2(1) = 23.22$, $p < 0.001$. The prevalence of heart disease was higher in males (55.3%) than in females (25.8%).\n\n## Exercise 5: Analyze heart disease by fasting blood sugar\n\nResearch question: *Is the presence of heart disease associated with fasting blood sugar?*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfbs_table <- table(heart_data$fbs, heart_data$target)\nfbs_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       \n        Heart Disease No Heart Disease\n  False           117              141\n  True             22               23\n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(fbs_table, margin = 1) * 100, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       \n        Heart Disease No Heart Disease\n  False          45.3             54.7\n  True           48.9             51.1\n```\n\n\n:::\n:::\n\n\nThe row percentages show similar heart disease prevalence in the two fasting blood sugar groups.\n\nThe expected cell counts are all larger than 5, so the chi-square test is appropriate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfbs_chisq <- chisq.test(fbs_table, correct = FALSE)\nfbs_chisq$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       \n        Heart Disease No Heart Disease\n  False     118.35644        139.64356\n  True       20.64356         24.35644\n```\n\n\n:::\n\n```{.r .cell-code}\nfbs_chisq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  fbs_table\nX-squared = 0.19339, df = 1, p-value = 0.6601\n```\n\n\n:::\n:::\n\n\nThere is no evidence of an association between fasting blood sugar and heart disease, $\\chi^2(1) = 0.19$, $p = 0.660$. The prevalence of heart disease was similar for patients with fasting blood sugar at or below 120 mg/dl (45.3%) and patients with fasting blood sugar above 120 mg/dl (48.9%).\n",
    "supporting": [
      "lab5_answers_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}