{
  "hash": "79c3aa71c535d48860c86f3b17a754c7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Medical Statistics - Answers lab 10\"\nsubtitle: \"Integrated exercises with the Cleveland heart disease dataset\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-location: right\n    code-overflow: wrap\n  pdf:\n    toc: false\nexecute:\n  warning: false\n  message: false\n  error: false\n  eval: true\n  echo: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Part A: ANCOVA\n\n### A1. Research question\n\nThe research question is whether resting blood pressure (`trestbps`) differs between males and females after adjusting for age.\n\nIn model notation, this is assessed with:\n\n$$\n\\text{trestbps} = \\beta_0 + \\beta_1 \\times \\text{age} + \\beta_2 \\times \\text{sex} + \\varepsilon\n$$\n\nThe coefficient for `sex` estimates the adjusted mean difference in resting blood pressure between males and females at the same age.\n\n### A2. Exploratory analysis\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  sex        n mean_trestbps sd_trestbps median_trestbps    q1    q3\n  <fct>  <int>         <dbl>       <dbl>           <dbl> <dbl> <dbl>\n1 Female    97          133.        19.4             132   120   140\n2 Male     206          131.        16.7             130   120   140\n```\n\n\n:::\n:::\n\n\nThe mean resting blood pressure is about 133 mm Hg for females and 131 mm Hg for males. The distributions are quite similar, with both groups having a median close to 130-132 mm Hg and an interquartile range of approximately 120 to 140 mm Hg.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab10_answers_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe scatterplot suggests a weak positive association between age and resting blood pressure. There is no strong visual evidence of a clearly non-linear relationship, so a linear adjustment for age is reasonable for this exercise.\n\n### A3. Additive ANCOVA model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = trestbps ~ age + sex, data = heart_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.125 -11.038  -0.838  10.587  66.507 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 102.8155     6.2686  16.402  < 2e-16 ***\nage           0.5478     0.1082   5.063 7.21e-07 ***\nsexMale      -1.3940     2.0928  -0.666    0.506    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.91 on 300 degrees of freedom\nMultiple R-squared:  0.08255,\tAdjusted R-squared:  0.07643 \nF-statistic:  13.5 on 2 and 300 DF,  p-value: 2.439e-06\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 90.4794612 115.151637\nage          0.3348881   0.760724\nsexMale     -5.5123753   2.724295\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=false title=\"Answer\"}\nAfter adjusting for age, males have an estimated resting blood pressure that is **1.39 mm Hg lower** than females.\n\nThe 95% confidence interval for the male-female adjusted difference is **-5.51 to 2.72 mm Hg**, and the p-value is **0.506**.\n\nThere is no evidence of a statistically significant difference in resting blood pressure between males and females after adjusting for age.\n:::\n\n### A4. Model assumptions and interaction\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab10_answers_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab10_answers_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe Q-Q plot should be checked for large departures from normality. In this dataset, the residuals are mostly compatible with approximate normality, although some tail deviations may be present.\n\nThe residuals-versus-fitted plot should be checked for curvature and unequal spread. There is no strong pattern suggesting that the additive linear model is inappropriate, although the model is not expected to explain all variation in resting blood pressure.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: trestbps\n            Sum Sq  Df  F value    Pr(>F)    \n(Intercept)  71768   1 250.4720 < 2.2e-16 ***\nage           7260   1  25.3374 8.328e-07 ***\nsex            104   1   0.3633    0.5471    \nage:sex        149   1   0.5216    0.4707    \nResiduals    85673 299                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=false title=\"Answer\"}\nThe age-by-sex interaction has p = **0.471**. This does not provide evidence that the association between age and resting blood pressure differs between males and females.\n\nTogether with the diagnostic plots, this suggests that the additive ANCOVA model is a reasonable model for these data.\n:::\n\n## Part B: Logistic regression and causal adjustment\n\n### B1. Preparing the outcome and exposure\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                  \n                     0   1\n  Heart Disease      0 139\n  No Heart Disease 164   0\n```\n\n\n:::\n:::\n\n\nThe outcome is coded so that `1` is the event of interest: heart disease. The value `0` corresponds to no heart disease.\n\n### B2. Unadjusted model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = target01 ~ chol, family = binomial, data = heart_data)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)  \n(Intercept) -0.989822   0.572848  -1.728    0.084 .\nchol         0.003339   0.002271   1.470    0.142  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 417.98  on 302  degrees of freedom\nResidual deviance: 415.78  on 301  degrees of freedom\nAIC: 419.78\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   OR     2.5 %   97.5 %\n(Intercept) 0.3716428 0.1209252 1.142180\nchol        1.0033444 0.9988878 1.007821\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                   OR     2.5 %  97.5 %\n(Intercept) 0.3716428 0.1209252 1.14218\nchol10      1.0339523 0.9889339 1.08102\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=false title=\"Answer\"}\nIn the unadjusted model, the odds ratio for a **1 mg/dl** increase in cholesterol is **1.003** with 95% CI **0.999 to 1.008** and p = **0.142**.\n\nFor a **10 mg/dl** increase in cholesterol, the odds ratio is **1.034** with 95% CI **0.989 to 1.081**.\n\nThe estimate is slightly above 1, but the confidence interval includes 1 and the p-value is not statistically significant. There is no clear evidence from the unadjusted model that cholesterol is associated with heart disease status.\n:::\n\n### B3. Causal diagram\n\nThe DAG contains the following arrows:\n\n- age -> cholesterol\n- age -> heart disease\n- sex -> cholesterol\n- sex -> heart disease\n- cholesterol -> heart disease\n- heart disease -> chest pain type\n\n```{mermaid}\nflowchart LR\n  age[Age] --> chol[Cholesterol]\n  age --> hd[Heart disease]\n  sex[Sex] --> chol\n  sex --> hd\n  chol --> hd\n  hd --> cp[Chest pain type]\n```\n\n::: {.callout-tip icon=false title=\"Answer\"}\nTo estimate the causal effect of cholesterol on heart disease, the adjusted model should include **age** and **sex**.\n\nAge and sex are confounders because they are causes of both cholesterol and heart disease. Chest pain type should not be adjusted for, because it is a consequence of heart disease in the DAG. Adjusting for a downstream consequence of the outcome is not part of the confounder adjustment set.\n:::\n\n### B4. Adjusted model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = target01 ~ chol + age + sex, family = binomial, \n    data = heart_data)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -5.909350   1.095393  -5.395 6.86e-08 ***\nchol         0.004829   0.002539   1.902   0.0572 .  \nage          0.062246   0.015120   4.117 3.84e-05 ***\nsexMale      1.631814   0.303194   5.382 7.36e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 417.98  on 302  degrees of freedom\nResidual deviance: 368.59  on 299  degrees of freedom\nAIC: 376.59\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     OR        2.5 %     97.5 %\n(Intercept) 0.002713949 0.0003171035 0.02322749\nchol        1.004841016 0.9998524987 1.00985442\nage         1.064224022 1.0331489166 1.09623381\nsexMale     5.113139619 2.8223350453 9.26332145\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                     OR        2.5 %     97.5 %\n(Intercept) 0.002713949 0.0003171035 0.02322749\nchol10      1.049478480 0.9985259652 1.10303099\nage         1.064224022 1.0331489166 1.09623381\nsexMale     5.113139619 2.8223350453 9.26332145\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=false title=\"Answer\"}\nAfter adjustment for age and sex, the odds ratio for a **1 mg/dl** increase in cholesterol is **1.005** with 95% CI **1.000 to 1.010** and p = **0.057**.\n\nFor a **10 mg/dl** increase in cholesterol, the adjusted odds ratio is **1.049** with 95% CI **0.999 to 1.103**.\n\nThe adjusted estimate is slightly larger than the unadjusted estimate. This suggests that age and sex act as confounders in the cholesterol-heart disease relationship, although the adjusted cholesterol association is still only borderline and is not statistically significant at the 0.05 level.\n:::\n\n## Part C: Building a prediction model\n\n### C1. Candidate model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = thalach ~ age + sex + cp + chol + fbs + trestbps, \n    data = heart_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-56.595 -11.437   2.564  13.335  43.999 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 187.98169   11.26288  16.690  < 2e-16 ***\nage          -0.97352    0.13553  -7.183 5.61e-12 ***\nsex1          1.02288    1.26254   0.810   0.4185    \ncp1           3.87332    3.29957   1.174   0.2414    \ncp2           6.33685    2.46981   2.566   0.0108 *  \ncp3           1.30012    2.09375   0.621   0.5351    \nchol          0.03689    0.02292   1.610   0.1086    \nfbs1         -0.46173    1.63623  -0.282   0.7780    \ntrestbps      0.07576    0.06904   1.097   0.2734    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.71 on 294 degrees of freedom\nMultiple R-squared:  0.2775,\tAdjusted R-squared:  0.2578 \nF-statistic: 14.11 on 8 and 294 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: thalach\n            Sum Sq  Df  F value    Pr(>F)    \n(Intercept) 108185   1 278.5688 < 2.2e-16 ***\nage          20039   1  51.5998 5.612e-12 ***\nsex            255   1   0.6564    0.4185    \ncp           16642   3  14.2838 1.030e-08 ***\nchol          1006   1   2.5906    0.1086    \nfbs             31   1   0.0796    0.7780    \ntrestbps       468   1   1.2041    0.2734    \nResiduals   114178 294                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nFor categorical predictors with more than two categories, such as `cp`, the Type III ANOVA table tests the predictor as a whole rather than only testing one dummy coefficient.\n\n### C2. Model selection\n\nFor this prediction exercise, backward elimination was used. The full candidate model was fitted first, and then the predictor with the largest p-value was removed as long as its p-value was greater than 0.10. This is reasonable for a prediction model because the goal is to obtain a more parsimonious model that keeps predictors with useful predictive information.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n   step removed  p_value\n  <dbl> <chr>      <dbl>\n1     1 fbs        0.778\n2     2 sex        0.429\n3     3 trestbps   0.235\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"age\"  \"cp\"   \"chol\"\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=false title=\"Answer\"}\nBackward elimination removed the following predictors:\n\n1. `fbs`, p = 0.778\n2. `sex`, p = 0.429\n3. `trestbps`, p = 0.235\n\nThe final prediction model retained **age**, **chest pain type (`cp`)**, and **cholesterol (`chol`)**.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = thalach ~ age + cp + chol, data = heart_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-58.701 -11.489   2.667  13.802  43.475 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        197.45207    9.05574  21.804  < 2e-16 ***\nage                 -0.92273    0.13019  -7.088 9.97e-12 ***\ncpAtypical angina    1.97796    4.99947   0.396 0.692660    \ncpNon-anginal pain  -2.84347    4.63234  -0.614 0.539797    \ncpAsymptomatic     -15.97952    4.42906  -3.608 0.000362 ***\nchol                 0.04241    0.02242   1.891 0.059539 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 19.68 on 297 degrees of freedom\nMultiple R-squared:  0.2723,\tAdjusted R-squared:   0.26 \nF-statistic: 22.22 on 5 and 297 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           2.5 %       97.5 %\n(Intercept)        179.630527922 215.27360552\nage                 -1.178934370  -0.66652072\ncpAtypical angina   -7.860912318  11.81682362\ncpNon-anginal pain -11.959841240   6.27289858\ncpAsymptomatic     -24.695840637  -7.26320698\nchol                -0.001716395   0.08653757\n```\n\n\n:::\n:::\n\n\nThe final fitted model is:\n\n$$\n\\widehat{\\text{thalach}} =\n197.45\n- 0.923 \\times \\text{age}\n+ \\text{chest pain type coefficient}\n+ 0.042 \\times \\text{cholesterol}.\n$$\n\nWith `Typical angina` as the reference category for chest pain type, the estimated chest-pain coefficients are approximately:\n\n- `Atypical angina`: 1.98\n- `Non-anginal pain`: -2.84\n- `Asymptomatic`: -15.98\n\n### C3. Prediction for a patient\n\nThe patient has:\n\n- age: 62 years\n- sex: female\n- chest pain type: typical angina\n- cholesterol: 240 mg/dl\n- fasting blood sugar > 120 mg/dl: false\n- resting blood pressure: 135 mm Hg\n\nOnly age, chest pain type, and cholesterol are used, because these are the predictors retained in the final model.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n150.4215 \n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=false title=\"Answer\"}\nThe predicted maximum heart rate for this patient is **150.4 beats per minute**.\n\nThis is calculated from the final model as:\n\n$$\n197.45 - 0.923 \\times 62 + 0.042 \\times 240 = 150.4.\n$$\n:::\n",
    "supporting": [
      "lab10_answers_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}