{
  "hash": "55e7aedae373433048028a7935504f13",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Medical Statistics – Answers lab 6\"\nformat:\n  html:\n    toc: true       \n    toc-depth: 3    \n    toc-location: right\n    code-overflow: wrap \n  pdf:\n    toc: false\nexecute:\n  warning: false\n  message: false\n  error: false\n  eval: true\n  echo: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Part 1: Pearson's correlation coefficient and simple linear regression\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 1\"}\nBased on the scatterplot, is there an indication of a linear association between `age` and `pocketdepth`? If so, is this association positive or negative?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 1\"}\nThe scatterplot suggests that there is a positive linear association between `age` and `pocketdepth`. As age increases, pocket depth tends to increase.\n:::\n\n### Pearson's Correlation Coefficient\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  pockets$age and pockets$pocketdepth\nt = 3.9647, df = 98, p-value = 0.0001398\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1891831 0.5295346\nsample estimates:\n     cor \n0.371786 \n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 2\"}\nWhat does the correlation coefficient tell us about the relationship between `age` and `pocketdepth`? Does this align with your interpretation of the scatterplot?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 2\"}\nThe correlation coefficient is approximately 0.37, indicating a moderate positive linear relationship between `age` and `pocketdepth`. This aligns with the interpretation of the scatterplot.\n:::\n\n::: {.callout-important icon=false title=\"Question 3\"}\nWhat is the p-value for the correlation coefficient test? Based on this p-value, do we have sufficient evidence to reject the null hypothesis?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 3\"}\nThe p-value for the correlation coefficient test is approximately 0.00014, indicating that we have sufficient evidence to reject the null hypothesis of no correlation between `age` and `pocketdepth`.\n:::\n\n### Fitting a Simple Linear Regression Model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pocketdepth ~ age, data = pockets)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.49289 -0.44376 -0.07903  0.49597  2.13335 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.85872    0.22862  16.878  < 2e-16 ***\nage          0.02054    0.00518   3.965  0.00014 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7535 on 98 degrees of freedom\nMultiple R-squared:  0.1382,\tAdjusted R-squared:  0.1294 \nF-statistic: 15.72 on 1 and 98 DF,  p-value: 0.0001398\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 4\"}\nIs the relationship between `age` and `pocketdepth` statistically significant (at α = 0.05)?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 4\"}\nThe estimated coefficient for `age` (0.021) is statistically significant with a p-value of 0.00014, indicating that the relationship between `age` and `pocketdepth` is statistically significant at α = 0.05.\n:::\n\n::: {.callout-important icon=false title=\"Question 5\"}\nHow does the p-value for `age` in the regression output compare to the p-value for the correlation coefficient test? Are they consistent with each other?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 5\"}\nThe p-value for `age` in the regression output (0.00014) and the p-value for the correlation coefficient test (0.00014) are consistent with each other. They both indicate a statistically significant relationship between `age` and `pocketdepth`.\n:::\n\n::: {.callout-important icon=false title=\"Question 6\"}\nWhat is the interpretation of the intercept and the coefficient for `age` in the regression output? \n:::\n\n::: {.callout-tip icon=false title=\"Answer question 6\"}\nThe intercept (3.859) represents the estimated pocket depth when age is 0, which may not have a meaningful interpretation in this context. The coefficient for `age` (0.021) represents the estimated change in pocket depth for each additional year of age.\n:::\n\n::: {.callout-important icon=false title=\"Question 7\"}\nBased on the fitted model, what is the expected pocket depth for a person who is 40 years old?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 7\"}\nThe expected pocket depth for a person who is 40 years old can be calculated using the intercept and coefficient from the regression output:\n3.859 + 0.021 * 40 = 4.699 mm\n:::\n\n::: {.callout-important icon=false title=\"Question 8\"}\nHow much of the variation in pocket depth is explained by age in this model?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 8\"}\nThe R-squared value of 0.138 indicates that approximately 14% of the variation in pocket depth is explained by age in this model.\n:::\n\n### Assumption Checking\n\n#### Normality of Residuals\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 9\"}\nDo the histogram and Q-Q plot suggest that the residuals are reasonably normally distributed?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 9\"}\nThe two plots suggest that the residuals are approximately normally distributed, with the histogram showing a roughly symmetric shape and the Q-Q plot showing the residuals closely following the diagonal line.\n:::\n\n#### Homoscedasticity and linearity\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 10\"}\nDoes the residual-versus-fitted plot suggest constant variance?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 10\"}\nThe residual-versus-fitted plot suggests that the variance of the residuals is relatively constant across the range of fitted values, indicating homoscedasticity.\n:::\n\n::: {.callout-important icon=false title=\"Question 11\"}\nDoes the residual-versus-fitted plot suggest any violation of the linearity assumption?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 11\"}\nThere is no obvious pattern or curvature in the residual-versus-fitted plot, indicating that the linearity assumption is not violated.\n:::\n\n## Part 2: ANCOVA (Analysis of Covariance)\n\n### Exploratory Data Analysis\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 12\"}\nWhat can you infer from the scatterplot about the relationship between `age`, `pocketdepth`, and `alcohol` consumption?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 12\"}\nAs discussed previously, the scatterplot suggests a positive relationship between `age` and `pocketdepth`, with higher pocket depths observed for older individuals. It also suggests that there is a U-shaped relationship between `alcohol` consumption and `pocketdepth`, with individuals consuming \"1-2 glasses/day\" having lower pocket depths compared to those consuming \"None\" or \">2 glasses/day\".\n:::\n\n### Fitting the ANCOVA Model\n\n#### R output\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pocketdepth ~ age + alcohol, data = pockets)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.35037 -0.45299 -0.06626  0.39746  1.76573 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             4.165461   0.270688  15.388  < 2e-16 ***\nage                     0.014849   0.005248   2.829  0.00568 ** \nalcohol1–2 glasses/day -0.394551   0.172383  -2.289  0.02428 *  \nalcohol>2 glasses/day   0.364565   0.188347   1.936  0.05586 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7069 on 96 degrees of freedom\nMultiple R-squared:  0.257,\tAdjusted R-squared:  0.2338 \nF-statistic: 11.07 on 3 and 96 DF,  p-value: 2.638e-06\n```\n\n\n:::\n:::\n\n\n#### SPSS output\n\n![Screenshot of the SPSS output tables](images/SPSS_lab6_q13.PNG)\n\n::: {.callout-important icon=false title=\"Question 13\"}\nBased on the ANCOVA model output, what is the expected difference in pocket depth between individuals who consume `\"None\"` and those who consume `\">2 glasses/day\"`, while controlling for age?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 13\"}\nBy default, the reference level for the `alcohol` variable is set to `\"None\"` in R and to `\">2 glasses/day\"` in SPSS. \n\nLooking at the R output, the coefficient for `\">2 glasses/day\"` is 0.365, which means that individuals who consume `\">2 glasses/day\"` are expected to have a pocket depth that is 0.365 mm higher than those who consume `\"None\"`, while controlling for age.\n\nLooking at the SPSS output, the coefficient for `\"None\"` is -0.365, which means that individuals who consume `\"None\"` are expected to have a pocket depth that is 0.365 mm lower than those who consume `\">2 glasses/day\"`, while controlling for age.\n\nTherefore, the expected difference in pocket depth between individuals who consume `\"None\"` and those who consume `\">2 glasses/day\"` is 0.365 mm, independent of the reference level chosen.\n:::\n\n::: {.callout-important icon=false title=\"Question 14\"}\nBased on the ANCOVA model output, what is the expected difference in pocket depth between individuals who consume `\"1-2 glasses/day\"` and those who consume `\">2 glasses/day\"`, while controlling for age?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 14\"}\nBy default, the reference level for the `alcohol` variable is set to `\"None\"` in R and to `\">2 glasses/day\"` in SPSS. \n\nLooking at the R output, the coefficient for `\">2 glasses/day\"` is 0.365 and the coefficient for `\"1-2 glasses/day\"` is -0.395. This means that individuals who consume `\">2 glasses/day\"` are expected to have a pocket depth that is 0.365 - -0.395 = 0.76 mm higher than those who consume `\"1-2 glasses/day\"`, while controlling for age.\n\nLooking at the SPSS output, the coefficient for `\"1-2 glasses/day\"` is -0.759, which means that individuals who consume `\"1-2 glasses/day\"` are expected to have a pocket depth that is 0.759 mm lower than those who consume `\">2 glasses/day\"`, while controlling for age.\n\nTherefore, the expected difference in pocket depth between individuals who consume `\"1-2 glasses/day\"` and those who consume `\">2 glasses/day\"` is 0.76 mm, independent of the reference level chosen.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: pocketdepth\n             Sum Sq Df  F value    Pr(>F)    \n(Intercept) 118.337  1 236.8042 < 2.2e-16 ***\nage           4.001  1   8.0055 0.0056789 ** \nalcohol       7.669  2   7.6729 0.0008104 ***\nResiduals    47.974 96                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 15\"}\nBased on the ANOVA table, is the `alcohol` variable significantly associated with `pocketdepth` after accounting for `age`?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 15\"}\nThe p-value for the `alcohol` variable in the ANOVA table is less than 0.05, indicating that the `alcohol` variable is significantly associated with `pocketdepth` after accounting for `age`.\n:::\n\n### Model Diagnostics\n\n::: {.callout-important icon=false title=\"Exercise\"}\nCheck the normality of residuals and homoscedasticity assumptions for the ANCOVA model.\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 15\"}\n\n#### Normality of Residuals\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n:::\n\n\nThe histogram and normal Q-Q plot of residuals shows that the residuals are approximately normally distributed, indicating that the normality assumption is not violated.\n\n#### Homoscedasticity\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe residuals vs. fitted plot shows that the residuals are randomly scattered around zero, indicating that the homoscedasticity assumption is not violated.\n:::\n\n## Part 3: Interactions in ANCOVA\n\n### Fitting the Interaction Model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pocketdepth ~ age * alcohol, data = pockets)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.35020 -0.45321 -0.06748  0.39755  1.76684 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 4.161e+00  3.811e-01  10.921   <2e-16 ***\nage                         1.494e-02  7.747e-03   1.928   0.0569 .  \nalcohol1–2 glasses/day     -3.862e-01  5.142e-01  -0.751   0.4544    \nalcohol>2 glasses/day       3.690e-01  6.538e-01   0.564   0.5738    \nage:alcohol1–2 glasses/day -2.082e-04  1.214e-02  -0.017   0.9863    \nage:alcohol>2 glasses/day  -9.585e-05  1.395e-02  -0.007   0.9945    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7144 on 94 degrees of freedom\nMultiple R-squared:  0.257,\tAdjusted R-squared:  0.2175 \nF-statistic: 6.503 on 5 and 94 DF,  p-value: 3.102e-05\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: pocketdepth\n            Sum Sq Df  F value  Pr(>F)    \n(Intercept) 60.865  1 119.2592 < 2e-16 ***\nage          1.897  1   3.7169 0.05688 .  \nalcohol      0.784  2   0.7678 0.46691    \nage:alcohol  0.000  2   0.0001 0.99985    \nResiduals   47.974 94                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: {.callout-important icon=false title=\"Question 16\"}\nBased on the output in the ANOVA table, is there a significant interaction between `age` and `alcohol` in predicting `pocketdepth`?\n:::\n\n::: {.callout-tip icon=false title=\"Answer question 16\"}\nThe p-value for the interaction term `age:alcohol` in the ANOVA table is approximately equal to 1, indicating that there is no interaction between `age` and `alcohol` in predicting `pocketdepth`.\n:::\n\n## Part 4: Relationship Between Smoking and Pocket Depth\n\nIn addition to information about alcohol consumption, the dataset also contains information about smoking habits. Explore the relationship between smoking and pocket depth, and how it interacts with age. You can use the same approach as in the previous sections to fit models, test for significance, and check assumptions.\n\n### Exploratory Data Analysis\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n### Fitting the ANCOVA Model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pocketdepth ~ age + smoking, data = pockets)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.3995 -0.5308 -0.1453  0.5331  2.2462 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.89031    0.22660  17.168  < 2e-16 ***\nage            0.01776    0.00534   3.326  0.00125 ** \nsmokingSmoker  0.32371    0.17709   1.828  0.07063 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7447 on 97 degrees of freedom\nMultiple R-squared:  0.1669,\tAdjusted R-squared:  0.1497 \nF-statistic: 9.718 on 2 and 97 DF,  p-value: 0.0001423\n```\n\n\n:::\n:::\n\n\nThe p-value for the `smoking` variable in the ANOVA table is 0.071, indicating that the `smoking` variable is not significantly associated with `pocketdepth` after accounting for `age`.\n\n### Model Diagnostics\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](lab6_answers_files/figure-html/unnamed-chunk-17-3.png){width=672}\n:::\n:::\n\n\nThe plots do not show any violations of the normality or homoscedasticity assumptions.\n\n### Fitting the Interaction Model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = pocketdepth ~ age * smoking, data = pockets)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.4160 -0.5382 -0.1353  0.5514  2.2096 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        3.778052   0.264041  14.309  < 2e-16 ***\nage                0.020622   0.006360   3.243  0.00163 ** \nsmokingSmoker      0.772509   0.567866   1.360  0.17690    \nage:smokingSmoker -0.009779   0.011755  -0.832  0.40751    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7459 on 96 degrees of freedom\nMultiple R-squared:  0.1729,\tAdjusted R-squared:  0.147 \nF-statistic: 6.689 on 3 and 96 DF,  p-value: 0.0003787\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: pocketdepth\n             Sum Sq Df  F value    Pr(>F)    \n(Intercept) 113.894  1 204.7350 < 2.2e-16 ***\nage           5.849  1  10.5145  0.001629 ** \nsmoking       1.029  1   1.8506  0.176898    \nage:smoking   0.385  1   0.6921  0.407507    \nResiduals    53.405 96                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe p-value for the interaction term `age:smoking` is 0.407, indicating that there is no significant interaction between `age` and `smoking` in predicting `pocketdepth`. \n\n\n",
    "supporting": [
      "lab6_answers_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}